URL="https://www.alibaba.ir/"
BROWSER="Chrome"
LOGIN_TXT="ورود با کلمه عبور"
LOGIN_BY_PASSWORD="xpath=//*[@class='btn is-md is-link']"
LOGIN_BUTTON="xpath://*[@class='relative']"
EMAIL_FIELD="xpath://label[contains(text(), 'آدرس ایمیل یا شماره موبایل')]/preceding-sibling::div/input"
PASSWORD_FIELD="xpath://*[@type='password']"
SUBMIT_BUTTON="xpath://button[@type='submit']"
HOTEL_PAGE="https://www.alibaba.ir/tour/iran-tehran/iran-kish_island?from=2025-01-22&to=2025-01-24&rooms=1"
HOTEL_BUTTON="xpath://button[contains(@class, 'btn is-md is-solid-secondary')]"
ROOM_SELECT_BUTTON="css:button.btn.is-lg.is-solid-secondary.is-block.my-2:first-of-type"
TOUR_SELECT_BUTTON="xpath://button[contains(@class, 'btn is-md is-solid-secondary')]"
EN_NAME_FIELD="xpath=//input[@name='name']"
EN_LAST_NAME_FIELD="xpath=//input[@name='lastName']"
FA_NAME_FIELD="xpath=//input[@name='namePersian']"
FA_LAST_NAME_FIELD="xpath=//input[@name='lastNamePersian']"
NATIONAL_CODE_FIELD="xpath=//input[@name='nationalCode']"
GENDER_FEILD="xpath=//input[@data-dropdown-id='al679068']"
FEMALE_GENDER="xpath=//a[@role='listitem' and span[contains(text(), 'زن')]]"
BIRTHDAY_DAY_FIELD="xpath=//span[contains(@class, 'flex items-center')]//svg"
BIRTHDAY_MONTH_FIELD="xpath=//label[@for='al335086']/preceding-sibling::div/input"
BIRTHDAY_YEAR_FIELD="xpath=//label[@for='al345392']/preceding-sibling::div/input"
CONTINUE_BUTTON="xpath=//button[contains(@class, 'btn is-lg is-solid-secondary is-block')]"
ASSERT_PAYMENT="xpath=//button[contains(@class, 'btn is-lg is-solid-secondary w-full')]"
VPN_CONFIRM="css:button[class*='is-solid-secondary']"
